apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyAiYXV0aHMiOiB7ICJnaGNyLmlvIjogeyAiYXV0aCI6ICJkbUZzZVd0eVlYTTZaMmh3WHpCSGFtRXhURU42WkVSbGJuZFdhbVZZTlRKVE0ySllXSFJuZVhSVVNERmxOMVJEYWc9PSIgfSB9IH0K
type: kubernetes.io/dockerconfigjson
